/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Boost } from "./Boost";
import { BoostCountArgs } from "./BoostCountArgs";
import { BoostFindManyArgs } from "./BoostFindManyArgs";
import { BoostFindUniqueArgs } from "./BoostFindUniqueArgs";
import { CreateBoostArgs } from "./CreateBoostArgs";
import { UpdateBoostArgs } from "./UpdateBoostArgs";
import { DeleteBoostArgs } from "./DeleteBoostArgs";
import { BoostService } from "../boost.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Boost)
export class BoostResolverBase {
  constructor(
    protected readonly service: BoostService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Boost",
    action: "read",
    possession: "any",
  })
  async _boostsMeta(
    @graphql.Args() args: BoostCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Boost])
  @nestAccessControl.UseRoles({
    resource: "Boost",
    action: "read",
    possession: "any",
  })
  async boosts(@graphql.Args() args: BoostFindManyArgs): Promise<Boost[]> {
    return this.service.boosts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Boost, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Boost",
    action: "read",
    possession: "own",
  })
  async boost(
    @graphql.Args() args: BoostFindUniqueArgs
  ): Promise<Boost | null> {
    const result = await this.service.boost(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Boost)
  @nestAccessControl.UseRoles({
    resource: "Boost",
    action: "create",
    possession: "any",
  })
  async createBoost(@graphql.Args() args: CreateBoostArgs): Promise<Boost> {
    return await this.service.createBoost({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Boost)
  @nestAccessControl.UseRoles({
    resource: "Boost",
    action: "update",
    possession: "any",
  })
  async updateBoost(
    @graphql.Args() args: UpdateBoostArgs
  ): Promise<Boost | null> {
    try {
      return await this.service.updateBoost({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Boost)
  @nestAccessControl.UseRoles({
    resource: "Boost",
    action: "delete",
    possession: "any",
  })
  async deleteBoost(
    @graphql.Args() args: DeleteBoostArgs
  ): Promise<Boost | null> {
    try {
      return await this.service.deleteBoost(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
